### ISSUE TITLE
Get an error importing the _robotsim module when calling import klampt

### ISSUE THREAD

**Issue by wanderin-earth** [krishauser/Klampt#104]
Hello! When I try running the Jupyter examples, an error occured and it reminded me that there's no _robotisim module. So I followed your instructions, using the Dependencies program to open _robotisim.pyd and found that WLDAP32.dll and WS2_32.dll had missing imports.
What should I do next?
Thanks.

**Comment by krishauser** [comment]
These are necessary system files, and it’s unclear why they aren’t working on your system. I suggest downloading them from a reputable site like the following link, and put the extracted DLLs in the folder containing robotsim.pyd.

https://www.dll-files.com/ws2_32.dll.html

**Comment by wanderin-earth** [comment]
I downloaded them and put them in the robotsim.pyd folder, but it was not so efficacious. And the error info seemed like this:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
D:\Anaconda\envs\klampt\Lib\site-packages\klampt\robotsim.py in swig_import_helper()
     22         try:
---> 23             fp, pathname, description = imp.find_module('_robotsim', [dirname(__file__)])
     24         except ImportError:

D:\Anaconda\lib\imp.py in find_module(name, path)
    295     else:
--> 296         raise ImportError(_ERR_MSG.format(name), name=name)
    297 

ImportError: No module named '_robotsim'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e61343c569da> in <module>
      7 
      8 import time
----> 9 from klampt import *
     10 from klampt.math import vectorops,so3,se3
     11 from klampt import vis

D:\Anaconda\envs\klampt\Lib\site-packages\klampt\__init__.py in <module>
      7 
      8 from .version import __version__
----> 9 from .robotsim import *
     10 import atexit
     11 atexit.register(destroy)

D:\Anaconda\envs\klampt\Lib\site-packages\klampt\robotsim.py in <module>
     31                 fp.close()
     32             return _mod
---> 33     _robotsim = swig_import_helper()
     34     del swig_import_helper
     35 else:

D:\Anaconda\envs\klampt\Lib\site-packages\klampt\robotsim.py in swig_import_helper()
     23             fp, pathname, description = imp.find_module('_robotsim', [dirname(__file__)])
     24         except ImportError:
---> 25             import _robotsim
     26             return _robotsim
     27         if fp is not None:

ModuleNotFoundError: No module named '_robotsim'

Would you be so kind as to help me with it? Thanks!

**Comment by krishauser** [comment]
Still a dependency issue, most likely. Could you show a screenshot of what libraries Dependencies says are missing?

**Comment by wanderin-earth** [comment]
![1](https://user-images.githubusercontent.com/47922199/122168929-6e4beb80-ceaf-11eb-80a7-c8549baf2fb8.png)
![2](https://user-images.githubusercontent.com/47922199/122168948-7146dc00-ceaf-11eb-9dc3-57ad2a46a136.png)
These are the two files.

**Comment by krishauser** [comment]
It appears that these need to be in your windows/system32 folder. Something seems amiss with your windows installation, as these are standard system files.
