### ISSUE TITLE
Recent Commits to KrisLibrary Broke Installation

### ISSUE THREAD

**Issue by yifanzhu95** [krishauser/Klampt#109]
When installing Klamp't from source, the following error shows up when compiling KrisLibrary: 

`/home/yifan/Klampt/Cpp/Dependencies/KrisLibrary/meshing/IO.cpp: In function ‘bool Meshing::LoadAssimp(const char*, std::vector<Meshing::TriMesh>&, std::vector<GLDraw::GeometryAppearance>&)’:
/home/yifan/Klampt/Cpp/Dependencies/KrisLibrary/meshing/IO.cpp:1017:15: error: ‘const struct aiScene’ has no member named ‘mMetaData’
     if(scene->mMetaData){
               ^~~~~~~~~
`

Checking out KrisLibrary to earlier commits from April fixed the problem.

**Comment by krishauser** [comment]
Should be fixed now
