### ISSUE TITLE
Tips for tuning Planners parameters

### ISSUE THREAD

**Issue by adithyamurali** [krishauser/Klampt#111]
Hi,

Thanks for the great repo! I'm currently trying to apply the `prm` planner on a 7dof arm planning problem. I'm using PRM since its a multi-query planner (the graph can be re-used for different planning problems). I'm able to get solutions in free space without any obstacles but the PRM struggles (and is very slow) when there is even a single obstacle is added in the environment. Based on reading the docs, I'm just specifying `knn:1` in the planner settings. Do you happen to have any tips for tuning PRM?

`rrt` just worked out of the box, with `restart:1` and `bidirectional:1`.

**Comment by krishauser** [comment]
There is a bit of experience and understanding of the algorithms that needs to be put into the parameter choices. Reasonable values for knn are typically in the range 5-20. PRMs can also accept a connectionThreshold argument, which is typically chosen between 0.01-0.25 times the length of the largest C-space dimension.

**Comment by krishauser** [comment]
Closed due to inactivity.
