### ISSUE TITLE
IK solver doesn't respect special joint and bad results

### ISSUE THREAD

**Issue by robotdelta** [krishauser/Klampt#112]
Hello, 
I tried to create a simple code under python to solve an IK to go from my current pose to a specific point (moved as I want in the simulation)
But I ran into a problem:
Whenever I try to resolve an IK with this rob file:
[bras robotse V3 rob.zip](https://github.com/krishauser/Klampt/files/7124333/bras.robotse.V3.rob.zip)
 the solver does not respect the special articulations like the affine articulation or the welded articulation (for the connection to the world). like this: 
normal: 
![joint OK](https://user-images.githubusercontent.com/74995239/132417245-1d232f9f-8792-4529-8050-9b4845b3722d.jpg)

broken: 
![joint broken](https://user-images.githubusercontent.com/74995239/132417253-f84c4e67-7a1b-425e-b6a6-1a67327e769e.jpg)

To solve this problem I tried several things and looked all over the python documentation but couldn't find anything. Do you have any idea what might solve this problem?

My second problem is that the solver considers the result OK even if the robot passes through itself.
And this kind of result may give a slight headache:
![bad IK](https://user-images.githubusercontent.com/74995239/132417268-5bb93ac4-1604-4e89-abb6-3c426c061672.jpg)

I tried to see with another robot to be sure that it was not my ROB file the problem and I have the same result with the TX90:
![bad IK TX90](https://user-images.githubusercontent.com/74995239/132417273-d738ab09-d867-482e-813f-60b6f57aa2d1.jpg)

Similarly, for this problem I looked in the python documentations but I did not see which corresponded to a collision parameter
Do you have any idea to work around this problem?

Thanks.

**Comment by krishauser** [comment]
Regarding your first issue -- thanks for bringing this up. I will look into it but it will be unlikely to be solved before version 0.9 is released.

Regarding the second, the standard solver does not perform collision checking. If you are using Python, the several [convenience functions](http://motion.cs.illinois.edu/software/klampt/latest/pyklampt_docs/klampt.model.ik.html#klampt.model.ik.solve_global) accept a "feasibilityCheck" argument which can be set to a function that checks for collisions (e.g., lambda: not robot.selfCollides())
