### ISSUE TITLE
.rob file creation

### ISSUE THREAD

**Issue by powerbling** [krishauser/Klampt#115]
Hi, me and my team are building a robot arm from scratch and are searching for a suitable controller software for IK and path planning.
Im wondering how I could create a .rob robot file to use with klampt's controllers.
I tried to search in documentation and in past issues but I couldn't find anything useful to understand.

Can someone point me in the right direction?
Thanks a lot.

**Comment by krishauser** [comment]
For future reference, please post usage questions on GitQ: [https://gitq.com/krishauser/Klampt](https://gitq.com/krishauser/Klampt)

Regarding your question, it's easiest to [read the docs](http://motion.cs.illinois.edu/software/klampt/latest/pyklampt_docs/Manual-FileTypes.html#robot-rob-files) or [look at some examples](https://github.com/krishauser/Klampt-examples/tree/master/data/robots) such as this [3R arm](https://github.com/krishauser/Klampt-examples/blob/master/data/robots/planar3R.rob). Or, you can convert from URDF (or just load URDF directly in Klampt).
