### ISSUE TITLE
model.sensing.image_to_points color bug

### ISSUE THREAD

**Issue by patricknaughton01** [krishauser/Klampt#119]
I was testing the 0.9 branch and I think this line
https://github.com/krishauser/Klampt/blob/37cbcf2df7af496fca5a02dc43af3f39a926ec96/Python/klampt/model/sensing.py#L369

needs to concatenate along dim 1 instead of 2 because at this point `pts` and `color` have been reshaped to only have 2 dimensions. As is, was giving me an error, making this change locally fixed it.

**Comment by krishauser** [comment]
Ah yes, thanks, can you make a PR?

**Comment by patricknaughton01** [comment]
Closed by #120
