### ISSUE TITLE
VoxelGrid convert from open3d not compatible with lastest version of Open3d

### ISSUE THREAD

**Issue by ShaoxiongYao** [krishauser/Klampt#121]
In `open3d_convert.py`, line 107 function `from_open3d`: `occupied = np.array(obj.voxels,dtype=np.int32)`. 

Looks like latest version of [open3d](http://www.open3d.org/docs/release/python_api/open3d.geometry.VoxelGrid.html) has removed direct access of voxels, this could be replaced by `occupied = np.array([v.grid_index for v in obj.get_voxels()],dtype=np.int32)`.

**Comment by krishauser** [comment]
Could you please submit a pull request with the fix? (Ideally, testing for the appropriate version of open3d or putting both in a try / except block)

**Comment by ShaoxiongYao** [comment]
Made a pull request in #122.
