### ISSUE TITLE
is it possible to do planning for a point robot via Klampt?

### ISSUE THREAD

**Issue by muk465** [krishauser/Klampt#125]
Hi guys I want to plan a path for  a point robot using rrt on a 3d image(3d numpy array) is it possible to do this using klampt? because when i was reading documentation i got the feeling that this library only supports manipulator kind of robots.Kindly help

**Comment by krishauser** [comment]
Yes, you may plan for point robots.  In Python there exists a base configuration space class CSpace and a motion planning class MotionPlan. You would subclass CSpace to add your hooks: http://motion.cs.illinois.edu/software/klampt/latest/pyklampt_docs/klampt.plan.cspace.html

One of the exercises has you doing exactly this. https://github.com/krishauser/Klampt-examples/tree/master/Python3/exercises/motionplanning

**Comment by krishauser** [comment]
Closed and moved to gitq
