### ISSUE TITLE
vis viewport setting

### ISSUE THREAD

**Issue by patricknaughton01** [krishauser/Klampt#126]
There might be a race condition when setting the viewport for visualizations. Using this example code:
```
import time
import klampt
from klampt import vis
from klampt.vis.glviewport import GLViewport
from klampt.model.create import primitives

world = klampt.WorldModel()
ro = primitives.box(1, 1, 1, world=world)
# world.add("ro", ro)
viewport = GLViewport()
viewport.w = 1280
viewport.h = 720
viewport.fov = 90
vis.add("world", world)
vis.setViewport(viewport)
vis.show()
time.sleep(0.5)
img = vis.screenshot()
print("IMG SIZE: ", img.shape)
while vis.shown():
    time.sleep(0.05)

viewport = GLViewport()
viewport.w = 1848
viewport.h = 1114
# viewport.fov = 30
vis.setViewport(viewport)
vis.show()
print("FOV: ", vis.getViewport().fov)
time.sleep(0.5)
img = vis.screenshot()
print("IMG SIZE: ", img.shape)
while vis.shown():
    time.sleep(0.05)
```
on my machine, sometimes the second output image will be 1280 x 720, other times it will be 1848 x 1114. The default view in the visualization also changes accordingly. The field of view seems to always report 30. If I uncomment the line that explicitly sets the fov, I haven't observed inconsistent behavior yet.

I originally noticed this when loading a viewport from a file (the resulting view was not consistent).

I was running klampt 0.9 (commit 37cbcf2df7af496fca5a02dc43af3f39a926ec96) for these tests.

**Comment by krishauser** [comment]
After show() is called, the visualization code is run in a separate thread.  Can you try using vis.lock() and unlock() around some of your calls to see if it fixes the problem?

**Comment by patricknaughton01** [comment]
I updated this as

```python
import time
import klampt
from klampt import vis
from klampt.vis.glviewport import GLViewport
from klampt.model.create import primitives

world = klampt.WorldModel()
ro = primitives.box(1, 1, 1, world=world)
# world.add("ro", ro)
viewport = GLViewport()
viewport.w = 1280
viewport.h = 720
viewport.fov = 90
vis.add("world", world)
vis.lock()
vis.setViewport(viewport)
vis.show()
vis.unlock()
img = vis.screenshot()
print("IMG SIZE: ", img.shape)
while vis.shown():
    time.sleep(0.05)

viewport = GLViewport()
viewport.w = 1848
viewport.h = 1114
# viewport.fov = 30
vis.lock()
vis.setViewport(viewport)
vis.show()
vis.unlock()
print("FOV: ", vis.getViewport().fov)
img = vis.screenshot()
print("IMG SIZE: ", img.shape)
while vis.shown():
    time.sleep(0.05)
```
I also tried only protecting the `setViewport` calls. In both cases, I get different sizes of the second image between runs. 

I also tried to put the lock and unlock calls around the `screenshot` call, this however prevented me from closing the vis window.

**Comment by krishauser** [comment]
Closing due to lack of updates.
