### ISSUE TITLE
loader type map backwards compatibility

### ISSUE THREAD

**Issue by patricknaughton01** [krishauser/Klampt#127]
It looks like the variable names for `extensionToTypes`, `typeToExtensions`, and `unsupportedJsonTypes` were changed in 0.9 to `EXTENSION_TO_TYPES` (and similar for the other two). 
https://github.com/krishauser/Klampt/blob/6650ddd1ce0a0ecfc1d9e6b28f56cd1f70036132/Python/klampt/io/loader.py#L27

This breaks compatibility with old versions of Klampt, noticed here in `alexandria.py` in the TRINA repo
https://github.com/uiuc-iml/TRINA/blob/6240035ef745c7a3eeeb9c14136aaf62923f159c/trina_devel/actions/alexandria.py#L12

Is this intended?

**Comment by krishauser** [comment]
Ah, I didn’t realize these constants were being used. It would be better to deprecate them incrementally, then.

**Comment by krishauser** [comment]
Fixed in most recent push to 0.9.
