### ISSUE TITLE
klampt_control error given joints with infinite limits

### ISSUE THREAD

**Issue by ShaoxiongYao** [krishauser/Klampt#128]
In version 0.9, `Python/klampt/apps/klampt_control.py` has error when robot joint has infinite limit, in `ControllerGUI -> onIdle` function, line 442-454
`
self.jointForms[i].sensedSlider.setValue(int(1024*(self.qsns[i]-qmin[j])/(qmax[j]-qmin[j])))
self.jointForms[i].commandSlider.setValue(int(1024*(self.qcmd[i]-qmin[j])/(qmax[j]-qmin[j])))
self.jointForms[i].targetSlider.setValue(int(1024*(qtgt[j]-qmin[j])/(qmax[j]-qmin[j])))`

For kinova Gen3 7DOF robot, the joint limits are `[-inf, -2.41, -inf, -2.66, -inf, -2.23, -inf], [0.0, inf, 2.41, inf, 2.66, inf, 2.23, inf, 0.0]`, which will cause error in `setValue` function.

I wonder if we should add a special condition checking if joint limits are infinite in this function.

**Comment by krishauser** [comment]
Should be fixed now.

**Comment by ShaoxiongYao** [comment]
I realized there is another place to add this fix in `klampt_control`, I can create a pull request soon.

**Comment by ShaoxiongYao** [comment]
Also, the certain joints of robotiq85 gripper have joint limits 0 for both `min` and `max`, how do we fix that?

`qmin = [0.0, 0.0, 0.0, 0.0, 0.0, -0.725, -0.725, 0.0, -0.725, 0.0], `
`qmax = [0.0, 0.0, 0.725, 0.0, 0.725, 0.0, 0.0, 0.725, 0.0, 0.0]`

**Comment by ShaoxiongYao** [comment]
Never mind, fixed in the latest pull.
