### ISSUE TITLE
Not implemented ControllerGUI components in klampt_control

### ISSUE THREAD

**Issue by ShaoxiongYao** [krishauser/Klampt#130]
Testing on branch 0.9

In `Python/klampt/apps/klampt_control.py`, line 264-266, in `ControllerGUI` function `__init__`, not implemented components `onMoveToCartesianPosition`, `onSetCartesianPosition` and `onSetCartesianVelocity` are used:

`self.panel.moveToCartesianPositionButton.clicked.connect(self.onMoveToCartesianPosition)
 self.panel.setCartesianPositionButton.clicked.connect(self.onSetCartesianPosition)
 self.panel.setCartesianVelocityButton.clicked.connect(self.onSetCartesianVelocity)`

I currently comment them out to use `klampt_control`.

**Comment by krishauser** [comment]
Fixed with latest version (still not functional... TBD).
