### ISSUE TITLE
URDF to Rob Converter

### ISSUE THREAD

**Issue by mehmedkoc** [krishauser/Klampt#133]
Dear Prof. Hauser,

I would like to mention an issue about the URDF file conversion to Rob file in order to edit and control my model by keyboard input (kbdrive.py), however, I could not see any app (RobotTest, SimTest, URDFtoRob, etc.) on the source of the master version on github. I have followed all instructions on "https://github.com/krishauser/Klampt/blob/master/Cpp/docs/Tutorials/Install-Linux.md" and installed it from the source. I have only access to "klampt_sim, klampt_path, klampt_thumbnails, and klampt_browser" apps. Should I focus on old Klamp't releases or edit/create a new one of the .rob files for my model? Thank you in advance.

Kind Regards.

**Comment by krishauser** [comment]
First you should know that Klampt natively reads URDF files, so it is unnecessary to convert to .rob.

These apps are built if you build from source or install via the Windows installer. In the former case they are located in Klampt/bin. In the latter case, they will be in Program Files (x86)/Klampt.
