### ISSUE TITLE
Windows Binaries not working

### ISSUE THREAD

**Issue by JakeSimoes** [krishauser/Klampt#134]
Hello. I'm just a newbie looking into running some inverse kinematics using the python library. I'd also like to use some of the applications in the windows binaries. After running them on several systems (from windows 11 to 7) I only get a command prompt window with ' This application failed to start because it could not find or load the Qt platform plugin "windows" in "" '. I specifically need the URDF to Rob converter to work as I need to make sure I have a good model for a NAO robot. Am I missing a requirement for the program to run? I have the visual studio runtime, but I'm not sure if something Qt related is required. Sorry if this is something I missed.

**Comment by krishauser** [comment]
This seems like an issue with some other program that works with Qt. Can you enter “ echo %QT_PLUGIN_PATH%” in a command line window to see what happens? This seems to be a common issue: https://forum.qt.io/topic/90293/could-not-find-or-load-the-qt-platform-plugin-windows-in/13

**Comment by JakeSimoes** [comment]
Thanks for your reply. I got "%QT_PLUGIN_PATH%" back. A user suggests that it means my Qt is not being hijacked by anything else. After running a quick file search, I found out there are dozens of other programs on my system running Qt just fine. So it doesn't seem to be something like that. Either way, it definitely shouldn't be anything like that since I tried it on a mint install of Windows 7 and 10. What kind of systems have you run the binaries on?

**Comment by krishauser** [comment]
Ah, this looks like a Qt deployment problem. Inside C:\Program Files (x86)\Klampt\bin\ create a folder called "platforms", and extract the following dll into C:\Program Files (x86)\Klampt\bin\platforms.

[qwindows.zip](https://github.com/krishauser/Klampt/files/7883975/qwindows.zip)

Could you see whether this works for you?

**Comment by JakeSimoes** [comment]
Yep, that fixed it! Everything is working as expected now. Thank you for your help!
