### ISSUE TITLE
Is it possible to get TCP position if manipulator joint values are known?

### ISSUE THREAD

**Issue by qwasko1212** [krishauser/Klampt#138]
I need to convert robot joint rotations to Cartesian coordinates of the TCP. 

Example:
joints: [val, val, val, val, val, val] → Cartesian coordinates: [x, y, z, roll, pitch, yaw]

The idea of this task is to compare real robot position with expected output. Real joints positions are read directly from the robot.
I have tried different methods, but none of them lead me to the proper result. Is it possible to perform this conversion using Python klampt?

**Comment by krishauser** [comment]
Reposting to gitq: https://gitq.com/krishauser/Klampt/topics/38/is-it-possible-to-get-tcp-position-if-manipulator-joint-values-are-known-repost-from-git-issues
