### ISSUE TITLE
`UseAffineConstraint` use

### ISSUE THREAD

**Issue by patricknaughton01** [krishauser/Klampt#143]
https://github.com/krishauser/Klampt/blob/791cba65f3cecab05d7511f8d4637c140e14fa19/Cpp/Modeling/Robot.cpp#L3790

We updated to Klampt 0.9 on TRINA. Trying to rebuild the robot masking code generated an error related to this function `UseAffineConstraint`, it looks like it's not defined anywhere.

**Comment by krishauser** [comment]
This was in the devel branch of KrisLibrary. The changes are now pushed to master.
