### ISSUE TITLE
RobotPose ignores scale factor parameters for meshes

### ISSUE THREAD

**Issue by mass2010chromium** [krishauser/Klampt#146]
example: https://answers.ros.org/question/273434/how-to-resize-meshes-in-urdf/?answer=273436#post-id-273436

**Comment by krishauser** [comment]
This works for me. You must be doing something wrong in setting the scale? Are you scaling the right geometry (visual vs collision)?

**Comment by mass2010chromium** [comment]
oh, i see. It looks like the collision geometry scaling is rendered, but visual geometry scaling isn't.

**Comment by krishauser** [comment]
Looks like you should be scaling both. The visual has scaling 1

**Comment by mass2010chromium** [comment]
Ah, I should've explained what is going on in the image.

Scale 1:1 would make the robot look "correct"; it looks like the 0.1 scaling of the collision geometry is being applied to the "base" link (making it look smaller).

**Comment by krishauser** [comment]
You need to set use_vis_geom to 0 or 1 in the klampt tag. Klampt doesn’t store separate visualization and collision geometries.
