### ISSUE TITLE
No documentation on editing C-space

### ISSUE THREAD

**Issue by Benoit-LdL** [krishauser/Klampt#151]
Hi,
Is there any documentation regarding the possible modifications of the C-space, but especially regarding adding constraints to the C-space? In the image below you mention this without referring to anything.

Kind regards,

Benoît Lagasse

<img src='https://gitq.com/files/raw/d9907ccad545fe7d7f8333334881803f1e2d2ea8.jpg' alt='question.jpg' width=741 />

---

submitted from [GitQ](https://gitq.com/krishauser/Klampt/topics/50/documentation-on-editing-c-space/1)

**Comment by krishauser** [comment]
Answered on Gitq.
