### ISSUE TITLE
Error when installing from source with Ubuntu 22.04.1

### ISSUE THREAD

**Issue by jstmn** [krishauser/Klampt#157]
Hi,

FYI: The command `make unpack-deps; make deps` was failing for me when I was installing Klampt by source.  I was getting the following error:
```
In file included from glui_add_controls.cpp:37:
./include/GL/glui.h:60:12: fatal error: GL/glut.h: No such file or directory
   60 |   #include <GL/glut.h>
      |            ^~~~~~~~~~~
compilation terminated.
```

Per https://stackoverflow.com/a/65194707/5191069 I installed the following: `sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev` and afterwards the command ran without any errors.

I figured this should be updated in the docs so that others don't need to run in this, or a some other solution should be implemented

Ubuntu version:
```
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

Thanks

**Comment by krishauser** [comment]
GLUI is not necessary for building Klampt unless you are building the C++ apps and Qt is not available. The GLUI apps are greatly reduced in functionality, so it is safe to ignore these errors. It may be better for us to just take GLUI out of the default build path and instead make it a backup. Keeping open as a TODO.

**Comment by krishauser** [comment]
Version 0.9.1 (currently on master) will remove GLUI dependencies on the default build path. Closing.
