### ISSUE TITLE
perform planning without simulation

### ISSUE THREAD

**Issue by M-Amin-Ali** [krishauser/Klampt#159]
Hey, 
I would like to run a few tests for the motion planning (klampt examples >> Python3). I would like to run the planning without a graphical window. Is it possible to set the window as invisible or to disable the graphical window?
thanks,
best,
Amin

**Comment by jstmn** [comment]
Hi @M-Amin-Ali,

Just remove all calls to the `vis` module - this would include `vis.add(...)`, `vis.setWindowTitle(...)`, etc.

- Jeremy
