### ISSUE TITLE
.dae elements are not loaded / visualized

### ISSUE THREAD

**Issue by jstmn** [krishauser/Klampt#163]
Hi,

I'm having trouble visualizing the .dae visual elements used in my urdfs.

The visual elements all have filepaths that are like 'meshes/visual/link2.dae', but it would seem they are being silently ignored. Here's the output of `world.loadRobot(urdf_filepath)`:
```
WorldModel::LoadRobot: /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/panda_arm_hand_formatted.urdf
joint mimic: no multiplier, using default value of 1 
joint mimic: no offset, using default value of 0 
URDFParser: Link size: 17
URDFParser: Joint size: 12
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/link0.stl (595 verts, 200 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/link1.stl (887 verts, 300 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/link2.stl (889 verts, 300 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/link3.stl (900 verts, 300 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/link4.stl (900 verts, 300 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/link5.stl (900 verts, 300 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/link6.stl (600 verts, 200 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/link7.stl (600 verts, 200 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/hand.stl (600 verts, 200 tris)
LoadAssimp: Loaded model /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/meshes/collision/finger.stl (96 verts, 32 tris)
URDFParser: Done loading robot file /home/jstm/Projects/jkinpylib/jkinpylib/urdfs/panda/panda_arm_hand_formatted.urdf
```

Here's what the robot looks like when visualized with Klamp't (these are all collision .stl's):
![image](https://user-images.githubusercontent.com/13972782/213599899-8684b9ee-0971-4bf3-bd7a-5e9072dcfa06.png)

And here's what the urdf looks like when visualized with [urdf-viz](https://github.com/openrr/urdf-viz) (the visual .dae's are shown here).
![image](https://user-images.githubusercontent.com/13972782/213599959-a551453a-a300-43e4-878f-0b702c360bd0.png)

I read in the [documentation](http://motion.cs.illinois.edu/software/klampt/latest/pyklampt_docs/Manual-IO.html?highlight=dae#:~:text=If%20you%20have%20used%20pip%20install%2C%20or%20build%20from%20source%20with%20Assimp%20support%2C%20then%20any%20file%20format%20that%20Assimp%20reads%20(STL%2C%20OBJ%2C%20DXF%2C%20Collada%20DAE)%20can%20also%20be%20read%20as%20a%20mesh) that the collada DAE filetype is supported so I wanted to see if there's someway I can have these .dae elements shown. 

This is with klampt version 0.9.0, installed with pip and I have assimp installed via apt with `libassimp-dev`.

Thanks!

**Comment by mass2010chromium** [comment]
If I recall, Klamp't only supports collision geometry. Visual geometry in the URDF doesn't show up in Klampt's simulation.

**Comment by krishauser** [comment]
You need to use the use_vis_geom attribute under the <klampt> tag:

https://github.com/krishauser/Klampt/blob/master/Cpp/docs/Tutorials/Import-and-calibrate-urdf.md

**Comment by jstmn** [comment]
Great, thanks.

Out of curiosity why is 'use_vis_geom' disabled by default?

**Comment by krishauser** [comment]
Klampt’s original use cases were as a replacement for simulation or for motion planning, so matching Gazebo behavior / MoveIt behavior was the intent of this decision. Lately people are using it as an RViz replacement, and many would prefer using vis geometries by default.

**Comment by jstmn** [comment]
I see, makes sense.
