### ISSUE TITLE
Issues with parsing urdf visual meshes using klampt

### ISSUE THREAD

**Issue by smeng9** [krishauser/Klampt#167]
Hi Professor,

Recently I am working on a using klampt to visualize some robot.
I have made a customized urdf file according to the ROS documentation http://wiki.ros.org/urdf/XML/link, however klampt cannot parse it correctly.
If I want to display the robot mesh, I cannot use the `<visual />` XML node, but need to use `<collision />` node instead. This is very confusing and should be considered a bug.

Here is a minimal reproducible example:

urdf file:
```
<?xml version="1.0"?>
<robot name="agv">
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="1.57079632679 0 0"/>
            <geometry>
                <mesh filename="agv.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>
</robot>
```

stl file:
[agv.stl.zip](https://github.com/krishauser/Klampt/files/11594626/agv.stl.zip)

code:
```
import klampt

world = klampt.WorldModel()
world.loadElement("agv.urdf")
```

expected output:
```
WorldModel::LoadRobot: agv.urdf
URDFParser: Link size: 6
URDFParser: Joint size: 1
ManagedGeometry: loaded agv.stl in time 0.728604s
URDFParser: Done loading robot file agv.urdf
```

actual output (missing the ManagedGeometry line, so no mesh can be displayed):
```
WorldModel::LoadRobot: agv.urdf
URDFParser: Link size: 6
URDFParser: Joint size: 1
URDFParser: Done loading robot file agv.urdf
```

**Comment by krishauser** [comment]
This is covered in the [Import URDF tutorial ](https://github.com/krishauser/Klampt/blob/master/Cpp/docs/Tutorials/Import-and-calibrate-urdf.md). TLDR: add the "<klampt use_vis_geom="1" />" tag to the URDF.
