### ISSUE TITLE
Triangle Mesh Backface Culling

### ISSUE THREAD

**Issue by j-polden** [krishauser/Klampt#175]
Hi All, 

I am visualizing some TriangleMesh data with the .vis package. I am wondering if it is possible enable back-face culling when i render them (so that a given triangle is visible from one side, but appears invisible when viewed from the opposite side).

Cheers

**Comment by krishauser** [comment]
Can you try glEnable(GL_CULL_FACE) in your script? (Functions are from PyOpenGL)

**Comment by krishauser** [comment]
Perhaps this needs to be called after the window is created, maybe also in the graphics thread. Worst comes to worse this could be solved with:

def graphicsSetup():
   glEnable(GL_CULL_FACE)

vis.show()
vis.threadCall(graphicsSetup)
