### ISSUE TITLE
lib/python3.7/site-packages/klampt/../Klampt.libs/libOpenGL-b706661f.so.0.0.0: undefined symbol: _glapi_tls_Current

### ISSUE THREAD

**Issue by clemense** [krishauser/Klampt#177]
After installing `Klampt-0.9.1.post4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` in a Pyhon 3.7.12 environment and testing `import klampt` I get:

```
  File "/home/clemens/miniconda3/envs/carbgym37/lib/python3.7/site-packages/klampt/__init__.py", line 9, in <module>
    from .robotsim import *
  File "/home/clemens/miniconda3/envs/carbgym37/lib/python3.7/site-packages/klampt/robotsim.py", line 18, in <module>
    from . import _robotsim
ImportError: /home/clemens/miniconda3/envs/carbgym37/lib/python3.7/site-packages/klampt/../Klampt.libs/libOpenGL-b706661f.so.0.0.0: undefined symbol: _glapi_tls_Current
```

Any hints?

**Comment by krishauser** [comment]
OK, we'll work on fixing this. What OS are you working on?

In the meantime, please downgrade to version 0.9.0 (pip install klampt=0.9.0)

**Comment by clemense** [comment]
Ah, thanks! Downgrading to 0.9.0 works.

OS is: Ubuntu 18.04.5 LTS

**Comment by krishauser** [comment]
The newest pip release "0.9.1.post5" should fix this problem. It's now relying on the system libOpenGL. Let me know if it doesn't work.

**Comment by clemense** [comment]
Just tested, this works. Thank you!
