### ISSUE TITLE
Typo in KrisLibrary/geometry/solid3/CMakeLists.txt

### ISSUE THREAD

**Issue by alexanderdsmith** [krishauser/Klampt#179]
When installing from source on Linux (Ubuntu 22.04) I found a small typo in KrisLibrary

Line 92:
`if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm" OR or ${CMAKE_SYSTEM_PROCESSOR} MATCHES ...`

Should have "or" removed:
`if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES ...`

**Comment by krishauser** [comment]
Thanks!
