### ISSUE TITLE
Is it possible to capture mouse wheel scrolling action ?

### ISSUE THREAD

**Issue by luewh** [krishauser/Klampt#180]
The goal is to have a function like `GLNavigationProgram.mousefunc(self,button,state,x,y)` to know the mouse wheel state.

**Comment by krishauser** [comment]
This isn't implemented yet because not all visualization backends will support mouse wheel capture. However, it may be possible to do this on Qt. I'll put this on the feature wish list

**Comment by krishauser** [comment]
The latest push to main now allows for mouse wheel updates.  See mousewheelfunc(self,dhorizontal,dvertical,x,y)!

**Comment by krishauser** [comment]
Adding a note that this is only available in OpenGL backends (Qt / GLUT)
