### ISSUE TITLE
No attribute error at moving_base_robot.make

### ISSUE THREAD

**Issue by MS-L-lia** [krishauser/Klampt#186]
(English is not my native language so I am using machine translation. Sorry if it is hard to read)

Function executed
```
klampt.model.create.moving_base_robot.make()
```

Error content

```
AttributeError: 'RobotModel' object has no attribute 'getTorqueMax'.
```

I am currently trying to use a robot with a floating joint to introduce a robot that can move freely in space.
I thought it would be a good idea to use this function to create a robot with a free-floating moving base in Klampt.
Then the aforementioned error occurred.

My predicted solution

I checked the API from the manual and found no function with that name, though,
I found a function with a similar name.

```
RobotModel.getTorqueLimits()
RobotModel.setTorqueLimits(tmax)
```

I believe that getTorqueMax() and setTorqueMax(tmax) used inside make() function are intended to describe these.
I have not checked the others at this time, so I am not sure if just fixing these will work as intended.

**Comment by krishauser** [comment]
Should be fixed in latest commit to master.
