### ISSUE TITLE
Segfault on Python3.10 when importing klampt 0.9.0

### ISSUE THREAD

**Issue by FlurinArner** [krishauser/Klampt#187]
**Issue resolved with `klampt 0.9.1`** (at least since `klampt 0.9.1.post5`)

In Python 3.10, if klampt version `0.9.0` is installed, loading the library immediately causes a SegFault. Although already resolved, I thought to create an issue (which can be closed immediately as resolved) for future reference if someone encounters the issue again (please let me know if this is undesired).

To resolve, install the newer klampt version with:
- `pip install klampt` (should get the newest version), or 
- by referencing the desired version directly `pip install klampt==0.9.1.post5`,
- or (if using Poetry) updating the reference in `pyproject.toml` to:
```
[tool.poetry.dependencies]
klampt = "0.9.1.post5"
```

This issue can be reproduced by running (note: installing `libopengl0` and `libgl1-mesa-glx` is necessary as detailed in #185):
```bash
docker run -dit python:3.10
docker exec -it $(docker ps -ql) bash
apt-get update && apt-get install -y libopengl0 libgl1-mesa-glx
pip install klampt==0.9.0
python -c "import klampt"
```

**Comment by krishauser** [comment]
Looks like this is fixed.
