### ISSUE TITLE
Python class GLSimulationProgram not found

### ISSUE THREAD

**Issue by AgarwalSaurav** [krishauser/Klampt#39]
Hi,

I was trying to run the the gltemplate.py file from the Python/demos directory. However, it gives an error 
`ImportError: cannot import GLSimulationProgram`

I searched for the class GLSimulationProgram but couldn't find it anywhere in the source code. It appears that GLSimulationProgram was changed to GLSimulationPlugin in the commit 
d95eac6a879eea440ccc70276eac5cb510730d50. 

The demo file sphero.py has the same issue.

Regards,
Saurav

P.S. I tried changing GLSimulationProgram ro GLSimulationPlugin in gltemplate.py but it doesn't seem to work directly due to changes in the number of parameters. I shall give a shot at fixing this.

**Comment by AgarwalSaurav** [comment]
I have created a pull request #40 which resolves the issue.

**Comment by krishauser** [comment]
Thank you, Saurav.  Sorry it took me so long to get back to you on this.
