### ISSUE TITLE
Couldn't initialize GLEW (Ubuntu 16.04)

### ISSUE THREAD

**Issue by atenpas** [krishauser/Klampt#44]
When trying to use a _CameraSensor_, I get this error:

> CameraSensor: Couldn't initialize GLEW, falling back to slow mode
>   glewInit() error: Missing GL version
>   This usually happens when an OpenGL context has not been initialized.  GL version is: (null)
> CameraSensor: GL framebuffers not supported, falling back to slow mode

This has happened on multiple computer systems in Ubuntu 16.04.

Not sure if this is useful, but **glewinfo** shows that _GLEW version 2.0.0_ is available on these systems.

The error happens [here](https://github.com/krishauser/Klampt/blob/master/Control/Sensor.cpp#L2094-L2118). Could it be related to [this](https://stackoverflow.com/questions/22371186/glewinit-fail-and-opengl-error-1282)?

**Comment by krishauser** [comment]
Hi Andreas, this warning occurs when an OpenGL context has not been set up by the time the simulation starts advancing. The camera sensor emulator uses OpenGL/GLEW for speed, otherwise it will just be slower than usual. 

As a workaround, try starting a visualization before taking any sim steps. Let me know if that works.

**Comment by atenpas** [comment]
I tried to start a visualization before taking any sim steps (see below) but that still gives me the same error.

```python
    world = WorldModel()
    for fn in sys.argv[1:]:
        res = world.readFile(fn)
        if not res:
            raise RuntimeError("Unable to load model "+fn)    

    vis.add("world",world)    
    vis.show()
    
    sim = SimpleSimulator(world)            
    sensor = sim.controller(0).sensor("rgbd_camera")
    sensor.kinematicReset()
    sensor.kinematicSimulate(world, 2.0)
```

**Comment by krishauser** [comment]
Ah, yes, this is strange. A quick test finds that this code below works. I believe it's because Qt does something weird with the OpenGL context if it doesn't have ownership of the current thread.  I will investigate other workarounds.

from klampt.vis.glcommon import GLPluginInterface

class MyPlugin(GLPluginInterface):
    def __init__(self,world,sensor):
        self.world = world
        self.sensor = sensor
    def initialize(self):
        print "Simulating sensor..."
        self.sensor.kinematicReset()
        self.sensor.kinematicSimulate(self.world, 2.0)
        return True


def sensortest():
    world = WorldModel()
    for fn in sys.argv[1:]:
        res = world.readFile(fn)
        if not res:
            raise RuntimeError("Unable to load model "+fn)    

    sim = SimpleSimulator(world)            
    sensor = sim.controller(0).sensor("rgbd_camera")

    sensorSimulator = MyPlugin(world,sensor)
    vis.pushPlugin(sensorSimulator)
    vis.add("world",world)    
    vis.show()
    vis.spin(0.1)
    vis.show(False)

if __name__ == "__main__":
    sensortest()

**Comment by krishauser** [comment]
This is a relatively unobtrusive workaround. A really tiny window should pop up which will kick start GLUT into creating an OpenGL context.

from OpenGL.GLUT import *

    world = WorldModel()
    for fn in sys.argv[1:]:
        res = world.readFile(fn)
        if not res:
            raise RuntimeError("Unable to load model "+fn)    

    glutInit ([])
    glutInitDisplayMode (GLUT_RGB | GLUT_DOUBLE | GLUT_DEPTH | GLUT_MULTISAMPLE)
    glutInitWindowSize (1, 1);
    windowID = glutCreateWindow ("test")
    sim = SimpleSimulator(world)            
    sensor = sim.controller(0).sensor("rgbd_camera")
    sensor.kinematicReset()
    sensor.kinematicSimulate(world, 2.0)

**Comment by atenpas** [comment]
@krishauser:  Just tested your 2nd code and it works on our machines as well! The workaround is enough for my purposes right now. Thank you for looking into this!
