### ISSUE TITLE
Robot links and objects disappear after klampt.robotsim.SimRobotSensor.kinematicSimulate()

### ISSUE THREAD

**Issue by mabelzhang** [krishauser/Klampt#52]
I'm having trouble getting correct RGB camera renders while using the workaround in #44. The visualization also seems to have bugs when kinematicSimulate() is called.

With and without the workaround, the behavior in the camera and vis visualization is different.
Vis: When I use the workaround, parts of the robot disappears, and all the RigidObjects disappear.
Camera sensor image: When I do not use the workaround, the render is wrong. With the workaround, the render is mostly correct, except the background color.

We have two scripts with slightly different setup, and the behavior is different in each (I'm not sure what makes them different, the two scripts are big files). The code to produce the RGB images is similar though, we're using:
`self.rgbd_cam = self.sim.controller(0).sensor("rgbd_camera")`
`self.rgbd_cam.kinematicReset ()`
`self.rgbd_cam.kinematicSimulate(self.world, 3.0)`
`self.rgb, self.depth = sensing.camera_to_images (self.rgbd_cam)`

Setup 1 screenshots:
Workaround off. Visualization and camera: correct behavior, but kinematicSimulate() is slow. (The objects are not in camera view, I haven't tested with objects in camera view yet.)
![](https://user-images.githubusercontent.com/7608908/33912744-18f55fd2-df65-11e7-9d53-f8da436b58ec.png)

Workaround on. Visualization: gripper and objects disappeared. Camera: background should be gray but is black.
![](https://user-images.githubusercontent.com/7608908/33912741-1713a354-df65-11e7-889a-8ca3fd02e93b.png)

Setup 2 screenshots:
Workaround off. Visualization: correct behavior. Camera: there should be objects in camera image, but there aren't.
![](https://user-images.githubusercontent.com/7608908/33912737-149af6e0-df65-11e7-9c9d-96e8aa6f4089.png)

Workaround on. Visualization: robot links and objects disappeared. Camera: Objects show up. But the background should be gray and it's black.
![env_workaroundon_robotlinksandobjectsdisappear_rgbbgblack](https://user-images.githubusercontent.com/7608908/33913658-bcf3677a-df68-11e7-8a24-c0526b4682b5.png)
I printed robot links appearance.getDraw(), and they are all True, but they aren't displayed correctly.

Any clues?

I can potentially strip down the two files and compare, but that will take some time as they're quite involved scripts. It seems the visualization part could be some graphics rendering bug, with geometries not being rendered, but they are probably there. This is only triggered by kinematicSimulate(), without this call, these things never happen.

Or, is there a better way to get camera images (I can try the simulation stepping way without kinematicSimulate next)? We need RGBD and depth, and the slow mode without the GLUT workaround takes a few seconds and we need a lot faster than that...
Thank you!!

**Comment by krishauser** [comment]
These are subtle opengl bugs, and are likely to have been fixed in Klampt 0.8.2. Please see the [Sensors manual](http://motion.cs.illinois.edu/software/klampt/latest/pyklampt_docs/Manual-Sensors.html#reading-sensors-in-code).
