### ISSUE TITLE
Custom Controller Config

### ISSUE THREAD

**Issue by sophiagudenrath** [krishauser/Klampt#53]
We are trying to use Klamp't with the Yaskawa SDA10F robot. We get the error I have pasted at the bottom when we run this command and try to simulate a path:
./SimTest ../ROSWorkspace/src/new-balance-mqp-vision/motoman/motoman_sda10f_support/urdf/klamp_model.rob

nbmqp@nbmqp-primary:~/Klampt$ ./SimTest ../ROSWorkspace/src/new-balance-mqp-vision/motoman/motoman_sda10f_support/urdf/klamp_model.rob
Initializing ODE...
RobotWorld::LoadRobot: ../ROSWorkspace/src/new-balance-mqp-vision/motoman/motoman_sda10f_support/urdf/klamp_model.rob
Reading robot file ../ROSWorkspace/src/new-balance-mqp-vision/motoman/motoman_sda10f_support/urdf/klamp_model.rob...
   Parsing robot file, 44 links read...
Loaded geometries in time 0.031161s, 20090 total primitive elements
Done loading robot file ../ROSWorkspace/src/new-balance-mqp-vision/motoman/motoman_sda10f_support/urdf/klamp_model.rob.
Creating WorldSimulation
Done.
Simulation initial state: 9188 bytes
BACKEND LOADED
Opened controller on address tcp://localhost:3456
set_q command does not work with the robot's controller
ODESimulator: Robot klamp_model energy 0.117455 exceeds threshold 0.00390225
ODERobot::SetVelocities: Error, Get/SetVelocities don't match
dq = 44    0.020751 -0.158581 0.0538793 1.94496 -0.0238093 -0.0269453 -2.47512 -2.10726 -0.878518 1.48329 -0.464283 -0.0918647 0.202579 0.438487 0 0 0 -13.0805 49.6453 -28.6095 0 13.2494 -53.1345 29.1621 0 2.43664 0.928671 -1.60538 0.552849 -0.136736 -0.297011 -0.763685 0 0 0 -26.0308 312.6 -51.4488 0 25.9675 -311.315 51.2257 0 -81.0413
from GetVelocities = 44    0.020751 -0.158581 0.0538793 1.94496 -0.0238093 -0.0269453 -2.47512 -2.10726 -0.878518 1.48329 -0.464284 -0.0918649 0.202579 0.438488 0 0 0 -13.0805 49.6453 -28.6096 0 13.2495 -53.1345 29.1621 0 2.43664 0.928672 -1.60538 0.552849 -0.136736 -0.297011 -0.763687 0 0 0 -26.0308 312.6 -51.4488 0 25.9676 -311.315 51.2257 0 -81.0413
Error: 0.000172902
did you remember to set the robot's configuration?
Press enter to continue...

Do you have any suggestions for fixing this? Thank you.

**Comment by krishauser** [comment]
Hi Sophia,

Sorry for the late reply. This usually occurs when a command is sent to the
controller before it gets to read the joint encoder sensors. Much like a
real robot has to go through a startup phase, the simulated robot will have
to take at least 1 time step before it can successfully accept commands.

Regards,
Kris Hauser
