### ISSUE TITLE
Error when installing Klampt using pip

### ISSUE THREAD

**Issue by sparshgarg23** [krishauser/Klampt#64]
Hi,
I am trying to install the python-api version of Klampt.However on executing the pip command,I got an error OpenSSL.SSL.wantreaderror.This was followed by several messages which said that another exception occured while handling the exception.
Could you tell me how to resolve this.

**Comment by krishauser** [comment]
This looks like it may be some pip version issue? See below.

https://stackoverflow.com/questions/49802238/cannot-use-pip-to-install-packages-it-reports-an-error-on-ssl-certificate

What OS and version of Python are you using?

**Comment by sparshgarg23** [comment]
Working on ubuntu 18.04 python 3.7

**Comment by sparshgarg23** [comment]
Hmm strange,I tried installing it on windows 10 Python 3.6.5, with pip version 10.0.1
it worked. 
Funny thing is I haven't upgraded pip on windows for a long time, but it still worked.
