### ISSUE TITLE
module 'Klampt' has no attribute 'simulator' 

### ISSUE THREAD

**Issue by hazimian** [krishauser/Klampt#67]
Hi There
Trying to learn to use Klampt, I was wondering which module does the API 'simulator()' belong to?
According to gl_vis.py it should be Klampt.simulator(), however I am getting the error that it does not exist.

thank

HA

**Comment by krishauser** [comment]
The correct call is klampt.Simulator() (note the capitalization). If you'd like to browse this, it's actually in the klampt.robotsim module, and all classes in there are imported upon import klampt.
