### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by greftly** [krishauser/Klampt#71]
Hi,

I installed Klampt with following [Klamp't Tutorial: Installation on Linux](https://github.com/krishauser/Klampt/blob/master/Cpp/docs/Tutorials/Install-Linux.md#linux-from-binaries). I'm getting error when I run `python kbdrive.py ../../data/tx90roll.xml `. 

> (base) task@task:~/Klampt/Klampt-examples/Python3/demos$ python kbdrive.py ../../data/tx90roll.xml
***  klampt.vis: using Qt5 as the visualization backend  ***
kbdrive.py: This example demonstrates how to drive a robot using keyboard input
RobParser: Reading robot file ../../data/robots/tx90pr2.rob...
RobParser:    Invalid robot property servoI on line 27
XmlParser: XmlRobot: error loading from file .
XmlParser: XmlWorld: Unable to load robot tx90pr2
Error opening or parsing world file ../../data/tx90roll.xml
Traceback (most recent call last):
  File "kbdrive.py", line 118, in <module>
    raise RuntimeError("Unable to load model "+fn)
RuntimeError: Unable to load model ../../data/tx90roll.xml

How Can I fix this?
Thank you.

**Comment by krishauser** [comment]
The line "RobParser: Invalid property servoI on line 27" is very odd. It should be internally converting the property name "servoI" into lowercase "servoi", but it doesn't seem to be doing that properly. Do you have an atypical system setup?  What system are you compiling under?

You could try going into the file "Klampt-examples/data/robots/tx90pr2.rob" and rewrite "servoI" as "servoi" on line 27 to see if that fixes the problem.

**Comment by greftly** [comment]
Thank you. It works well now. But all of .rob files written as "servoI".
I'm using Ubuntu 18.04.4 
Regards.
