### ISSUE TITLE
Can't use klampt commands

### ISSUE THREAD

**Issue by mn-banjar** [krishauser/Klampt#77]
Hi,
I'm using klampt on Ubuntu, I got this error when I'm running any instruction started with `bin`, the error bellow was gotten when running `bin/SimTest Klampt-examples/data/athlete_fractal_1.xml`

`bash: bin/SimTest: No such file or directory
`
How can I use them?

Thank you.

**Comment by krishauser** [comment]
These programs are compiled when you build Klampt from source, and you use “make apps” to build them.

**Comment by mn-banjar** [comment]
> These programs are compiled when you build Klampt from source, and you use “make apps” to build them.

Thank you, I solved the issue by running `make` to build the missing files
