### ISSUE TITLE
Some issues and improvement on python bindings

### ISSUE THREAD

**Issue by smeng9** [krishauser/Klampt#79]
Hi, we are testing the latest Klampt with TRINA project.

Issues:
- [x] GLEW_DIR seems not detected properly in cmake-gui even after dependencies are updated in ld.so.conf.d
     This will cause import issues in _robotsim module with error "undefined symbol: __glewGenRenderBuffers"
     Update: Issue caused by dependencies KrisLibrary, see pull requests https://github.com/krishauser/KrisLibrary/pull/14

- [x] Some system does not have "alias python=python3" which may fail python detection in Python/CMakeLists.txt
     Consider changing to IF(PYTHON OR PYTHON2 OR PYTHON3)

Improvements:
- [x] Update Setup in Cpp/docs/Tutorials/install-Linux.md with apt-install python3-dev for latest python

- [x] Update FindROS.cmake for latest version of ROS

Thanks

**Comment by krishauser** [comment]
Done, thanks!
