### ISSUE TITLE
Regression: Geometry3D groups cannot be displayed properly

### ISSUE THREAD

**Issue by smeng9** [krishauser/Klampt#83]
After bumping klampt installed from pypi from 0.8.3 to 0.8.5, Geometry3D groups cannot be displayed in visualization. That causes meshes disappearing on TRINA GUI.

I have adapted the examples at the bottom of https://github.com/krishauser/Klampt/blob/master/Python/docs/source/Manual-Modeling.rst into the following zip. The following code cannot display a shelf on 0.8.5, but can display a shelf on 0.8.3. If we display Geometry3D one by one manually, they can still be displayed. However after calling setGroup() it cannot display anything in that group.

[geometry3d_regression.zip](https://github.com/krishauser/Klampt/files/5687534/geometry3d_regression.zip)

Additionally there seems a typo in the provided sample code https://github.com/krishauser/Klampt/blob/master/Python/docs/source/Manual-Modeling.rst w = WorldModel() probably should be changed to world = WorldModel()

**Comment by smeng9** [comment]
The Geometry3D group visualization issues seems is fixed. Closing this now. Thank you.

However the visualized shelf seems have a diagonal line at each side of the surface compared to before. Is this due to the new rendering features?

**Comment by krishauser** [comment]
Can you show a screenshot?

**Comment by smeng9** [comment]
Sure, before and after comparison.

![before](https://user-images.githubusercontent.com/38666763/102405774-425ab680-3faf-11eb-91a6-099f668b9c27.PNG)
![after](https://user-images.githubusercontent.com/38666763/102405783-44247a00-3faf-11eb-9833-98a27178caa0.PNG)

**Comment by krishauser** [comment]
Does it go away if you call

appearance.setDraw(Appearance.EDGES,False)?

**Comment by smeng9** [comment]
Setting the edges to False seems have no effect on rendering.

**Comment by krishauser** [comment]
OK, it should be fixed with the latest commit to KrisLibrary.
