### ISSUE TITLE
CSpace calculation

### ISSUE THREAD

**Issue by hugosciascia** [krishauser/Klampt#85]
Hello !

Thank you for this usefull library ! 

I am working on a project where I need to get the C-Space of my robot (currently 2-DOF and 3-DOF, but the idea is to reach a 6-DOF).

The robot (2-DOF or 3-DOF) is inside an environnement, composed by some geometrics shapes. So, in order to get the motion planning, I want to know first how the C-Space will be calculated.

I do not understand how can I make a code which give me only the CSpace in result. Is it possible ? Or we have to give the C-Space ourselves ? 
I do not find the explanations in your Klampt-examples repository.

Thanks a lot in advance,
Hugo

**Comment by krishauser** [comment]
I suggest you consult the manual about the [planning tools](http://motion.cs.illinois.edu/software/klampt/latest/pyklampt_docs/Manual-Planning.html#api-summary). It is not clear what you mean by compute the C-space, but you can create a C-space object that will be used for planning rather easily. Or, you can use the convenience function planToConfig.

**Comment by hugosciascia** [comment]
Thanks for you answer.

I would like to know if your software is able to create a C-Space object for a 6-DOF Robot Arm. 
But I have trouble with the organization of your files and how to run them, maybe you can show me an example ?

For example, I run klampt_browser, then select tx90blocks.xml.
The file tx90blocks.xml show an articulated robot inside an environment composed of 5 blocks on a "plane/table", and a box on the other side.

From this file, which represent a really good environment close to a bin-picking application, I would like to get the C-Space (RobotCSpace, ContactCSpace or StanceCSpace) and then avoid the Ccollisions to do the bin-picking task.
Because I suppose that none of the robot axis should touch the table or the box for example ?

If you have an example I would be so much gratefull ! 👍
