### ISSUE TITLE
mount sub-robots to world frame

### ISSUE THREAD

**Issue by jshoving** [krishauser/Klampt#91]
Hello!

I've been using v0.8.1 for a while and was avoiding updates to keep my code stable. new members of my team have noted that this version is no longer hosted, and went for v0.8.2. Now that I'm trying this version, as well as the latest 0.8.6, it looks like mounting a sub-robot to the world frame is no longer supported.

Was the ability to mount a sub-robot to the world frame via `mount -1 "subrobot.rob" as subrobot ` an accident previously, or is that functionality no longer supported by design? Definitely recognize that it is roughly the same to use two separate robots in the same worldmodel, but this backdoor did have some benefits for me in ease of getting relative transforms, IK of two robots at the same time, abstraction of my state machine simulation that initially starts with the two robots welded together, etc

Any tips in general of how to handle? Or would you also be open to hosting v0.8.1 again so that my team can continue to install as new members onboard?
![image](https://user-images.githubusercontent.com/9540047/110538024-5870a280-80d8-11eb-8325-1c1b6634b5fe.png)

Thanks,
Jason

**Comment by jshoving** [comment]
using the setParent(-1) command is basically what I'm going for, but that doesn't seem to take -1 as a valid argument
![image](https://user-images.githubusercontent.com/9540047/110715964-18ceb700-81bb-11eb-8519-69869698104e.png)

**Comment by jshoving** [comment]
and defining the robot (two 6dof bodies floating independently) with the following does load successfully, but doesn't actually use the worldframe as the parent for link 6
![image](https://user-images.githubusercontent.com/9540047/110716321-c641ca80-81bb-11eb-9251-94612c409937.png)
![image](https://user-images.githubusercontent.com/9540047/110716493-233d8080-81bc-11eb-9a58-c1f2b0b69f0b.png)
all elements in columns 0-5 should be 0 as my intent is to make link 6 independent from links 0-5

**Comment by krishauser** [comment]
Ah, this is regrettably a regression.  I introduced the bug when I made it easier to refer to links by name.  The latest version of master, if you build from source, will fix the problem.

**Comment by jshoving** [comment]
Thanks for the quick response and action! We'll work on building from source for the future - the problem on our end is solved by reverting to an older version of python and continuing to use v0.8.1.

**Comment by krishauser** [comment]
Ok, the fix will be in the 0.8.7+ release.
