### ISSUE TITLE
Displaying geometry of franka emika's panda robot URDF throws segfault

### ISSUE THREAD

**Issue by smeng9** [krishauser/Klampt#95]
I have tried to load and visualize the robot model with klampt. However I get into a segmentation fault below.

![Screenshot from 2021-03-29 21-48-18](https://user-images.githubusercontent.com/38666763/112926867-ae35da80-90d9-11eb-9440-65aac392f1b1.png)

I first cloned the git repo of https://github.com/frankaemika/franka_ros 
Then I converted panda_arm_hand.urdf.xacro file to urdf in ./franka_description/robots/ using `$ xacro --inorder panda_arm_hand.urdf.xacro > panda_arm_hand.urdf` in http://wiki.ros.org/urdf/Tutorials/Using%20Xacro%20to%20Clean%20Up%20a%20URDF%20File 
Finally I followed the tutorial of https://github.com/krishauser/Klampt/blob/master/Cpp/docs/Tutorials/Import-and-calibrate-urdf.md to add `<klampt package_root="../.."  use_vis_geom="1" />`

However during visualization the Meshing::MergeVertices from KrisLibrary somehow crashes.

I will also attach a minimal example in the zip file. 
[franka_description.zip](https://github.com/krishauser/Klampt/files/6225866/franka_description.zip)
To reproduce the issue we need to extract then run display_urdf in ./robots folder.

**Comment by krishauser** [comment]
This is a problem with KrisLibrary, and the most recent update should fix it. Make sure to rebuild KrisLibrary and the Python API (you may need to clear the Python/build folder)

Briefly, the mesh has some 2-element faces. Why? Beats me...

You will need to add the Klampt tag flip_yz="1", too.
