### ISSUE TITLE
Estimation of mass returns non- positive definite inertia matrix 

### ISSUE THREAD

**Issue by smeng9** [krishauser/Klampt#99]
Hi Professor,

I have encountered a problem with rigidObjects when using the Simulator. 

For some specific objects that I tried to add to the world, it will prevent the simulator running.
The inertia matrix returned should be positive definite all the time.

I have created a minimum example that shows the issue.
[bug_reproduce.zip](https://github.com/krishauser/Klampt/files/6385942/bug_reproduce.zip)

Thanks.

**Comment by krishauser** [comment]
I found the issue. The problem is that your mesh is basically one-sided, and the method used to estimate volumetric inertia assumes the mesh is watertight. Hence, its results are way, way off.  For geometries that are one-sided, you should use surfaceFraction = 1 in the estimate.
